# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Windows package

on:
#  push:
#    branches: [ github-actions-* ]
  #  pull_request:
  #    branches: [ main ]

  #on:
  release:
    types:
      - created

defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
      - name: Set up JDK 18 for x64
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'
          java-package: jdk+fx
          architecture: x64
      - name: Get version
        run: echo project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
      - name: test
        run: echo test ${{ env.project_version }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Copy jar
        run: mkdir jar && cp shade/*.jar jar
      - name: Package jar for Windows
        run: jpackage --input jar --main-jar LATIC-${{ env.project_version }}.jar --name LATIC --description "LATIC - A Linguistic Analyzer for Text and Item Characteristics" --vendor "Florian Kl√ºckmann" --win-shortcut --win-menu --win-dir-chooser --win-per-user-install --icon ./src/main/resources/software/latic/latic-square-256.png -d win --app-version ${{ env.project_version }}
      - name: Copy documentation and installation guide
        run: |
          mkdir win/english
          mkdir win/deutsch
          cp ./src/main/resources/software/latic/documentation_en.pdf "win/english/LATIC ${{ env.project_version }} Documentation.pdf"
          cp ./src/main/resources/software/latic/documentation_de.pdf "win/deutsch/LATIC ${{ env.project_version }} Dokumentation.pdf"
          cp "./supplemental-material/en/Instructions Installing and Starting LATIC on Windows.docx" "win/english/Instructions Installing and Starting LATIC on Windows.docx"
          cp "./supplemental-material/de/Anleitung LATIC installieren und starten Windows.docx" "win/deutsch/Anleitung LATIC installieren und starten Windows.docx"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: win/*
      - uses: actions/upload-artifact@v2
        with:
          name: LATIC-${{ env.project_version }}-Windows-EN-DE
          path: win/*
